### ISSUE TITLE
[BUG] Poll Interval not shown on creating slave

### ISSUE THREAD

**Issue by madejackson** [modbus2mqtt/server#33]
When creating a slave, the Poll Interval field is hidden. It can be enabled by changing Poll Interval Selection field to  Trigger and back to Interval.

![image](https://github.com/user-attachments/assets/0e4ba222-5a7e-4e49-856b-ac3a4b351f86)

**Comment by modbus2mqtt** [comment]
If the poll mode is trigger, polling can be triggered by a Matt message only. Otherwise it triggers in the trigger interval. So, it works as expected. The poll interval is not used in trigger mode. This is useful if you want to make sure that a value is updated after a certain event.

**Comment by madejackson** [comment]
I think you missunderstood.

Look on the picture at the Slave Settings of Slave 2. Poll Intervall is missing. It only appears after fumbling with poll interval selection.

**Comment by volkmarnissen** [comment]
Sorry, I didn't check the image and the description properly.
This will be fixed in next release
