### ISSUE TITLE
[Manufacturer related] Unable to use negative temperatures

### ISSUE THREAD

**Issue by albgit** [modbus2mqtt/server#39]
In my specification there are several registers that have default negative values.
Adding it to modbus2mqtt gives me a positive integer.
In manufacturer pdf data types is "Unsigned Integer".
Example "Lower AT-Heat", value:-20℃, values by modbus2mqtt: 65516.
This is the specification:
[hmi-120.zip](https://github.com/user-attachments/files/17616507/hmi-120.zip)
Pdf from the manufacturer:
[modbus-versati-iii-en.pdf](https://github.com/user-attachments/files/17616519/modbus-versati-iii-en.pdf)

**Comment by volkmarnissen** [comment]
This will be implemented in the next release.
Signed integer will be configurable in the number format list.

**Comment by albgit** [comment]
Updated to 0.16.12.
I changed the type to signed int16 with no changes (value 65516).
