### ISSUE TITLE
Template variable warning: 'dict object' has no attribute 'ch3c1currentvalue' when rendering '{{ value_json.ch3c1currentvalue }}'

### ISSUE THREAD

**Issue by arturmietek** [modbus2mqtt/server#63]
I have a few thousand of messages like in title when value of current is 0 provided by modbus device.
State of entity is unknown so i guess that when modbus register is zero then modbus2mqtt assumes that reading failed. In my case I use only second channel. But when switch monitored device to channel one then readings was correct with nice mA values.

![image](https://github.com/user-attachments/assets/09ce9b91-cd25-4122-9997-ede71cb90a10)
![image](https://github.com/user-attachments/assets/6e1cdf8c-bb8c-49f4-a17c-f69ac5688124)
![image](https://github.com/user-attachments/assets/f18f46a3-31b6-4dee-87f7-022a9e011387)

**Comment by volkmarnissen** [comment]
I got the issue. Will be fixed in 0.16.16
