### ISSUE TITLE
Update Modbus <=> MQTT from 0.16.16 to version 0.16.17 fails

### ISSUE THREAD

**Issue by claespol** [modbus2mqtt/server#71]
Can't install modbus2mqtt/modbus2mqtt-aarch64:0.16.17: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=0.16.17&fromImage=modbus2mqtt%2Fmodbus2mqtt-aarch64&platform=linux%2Farm64: Not Found ("manifest for modbus2mqtt/modbus2mqtt-aarch64:0.16.17 not found: manifest unknown: manifest unknown")

system info
 Add-on version: 0.16.16
 There is an update available for this add-on!
 Latest add-on version: 0.16.17
 Please consider upgrading as soon as possible.
 System: Home Assistant OS 14.1  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2024.12.5
 Home Assistant Supervisor: 2024.12.0

Thx 

Paul

**Comment by albgit** [comment]
Same here

**Comment by modbus2mqtt** [comment]
There was a Build issue, it‘ll be solved tomorrow.Von meinem iPhone gesendetAm 27.12.2024 um 16:28 schrieb albgit ***@***.***>:﻿
Same here

**Comment by modbus2mqtt** [comment]
Use 0.16.18. There were build issues.
